# Generated by Django 5.0.2 on 2024-02-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vision", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="cat",
            field=models.IntegerField(
                choices=[
                    (1, "Frontend"),
                    (2, "Backend"),
                    (3, "Database"),
                    (4, "Devops"),
                    (5, "DSA"),
                ],
                max_length=50,
                verbose_name="Category",
            ),
        ),
    ]
